package io.github.aquerr.rentacar.domain;

public enum ApiExceptionCode
{
    IMAGE_NOT_FOUND,
    COULD_NOT_SAVE_IMAGE,
    BAD_CREDENTIALS,
    USER_LOCKED,
    USER_NOT_ACTIVATED,
    USER_NOT_EXIST,
    ACCESS_DENIED,
    PROFILE_NOT_FOUND,
    ACTIVATION_TOKEN_USED,
    ACTIVATION_TOKEN_EXPIRED,
    ACTIVATION_TOKEN_NOT_FOUND,
    USER_EXISTS,

}
