CREATE TABLE account_activation_token
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT                   NOT NULL,
    token                VARCHAR(64) UNIQUE       NOT NULL,
    expiration_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    used                 BOOLEAN DEFAULT 1        NOT NULL,
    CONSTRAINT fk_account_activation_token_user_id FOREIGN KEY (user_id) REFERENCES rentacar_user (id)
);