CREATE TABLE reservation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INTEGER      NOT NULL,
    user_id    BIGINT       NOT NULL,
    date_from  DATE         NOT NULL,
    date_to    DATE         NOT NULL,
    status     VARCHAR(100) NOT NULL,
    CONSTRAINT fk_reservation_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicle (id),
    CONSTRAINT fk_reservation_user_id FOREIGN KEY (user_id) REFERENCES rentacar_user (id)
);