CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credentials_id BIGINT NOT NULL,
    token VARCHAR(64) UNIQUE NOT NULL,
    expiration_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    used BOOLEAN DEFAULT 1 NOT NULL,
    FOREIGN KEY (credentials_id) REFERENCES user_credentials (id)
);