DROP TABLE password_reset_token;
DROP TABLE account_activation_token;

CREATE TABLE challenge_token
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT                   NOT NULL,
    operation_type       VARCHAR(64)              NOT NULL,
    token                VARCHAR(64)              NOT NULL,
    created_date_time    TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    used                 BOOLEAN DEFAULT 1        NOT NULL,
    CONSTRAINT fk_challenge_token_user_id FOREIGN KEY (user_id) REFERENCES rentacar_user (id)
);