CREATE TABLE rentacar_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE user_credentials
(
    user_id             BIGINT PRIMARY KEY,
    username            VARCHAR(36) UNIQUE       NOT NULL,
    email               VARCHAR(64) UNIQUE       NOT NULL,
    password            VARCHAR(255)             NOT NULL,
    activated           BOOLEAN DEFAULT 0        NOT NULL,
    locked              BOOLEAN DEFAULT 0        NOT NULL,
    created_date_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    activated_date_time TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_user_credentials_user_id FOREIGN KEY (user_id) REFERENCES rentacar_user (id)
);