CREATE TABLE user_authority
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT NOT NULL,
    authority VARCHAR(255),
    CONSTRAINT fk_user_authority_user_id FOREIGN KEY (user_id) REFERENCES rentacar_user (id)
);