CREATE TABLE reservation
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id      INTEGER      NOT NULL,
    user_profile_id BIGINT       NOT NULL,
    date_from       DATE         NOT NULL,
    date_to         DATE         NOT NULL,
    status          VARCHAR(100) NOT NULL,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle (id),
    FOREIGN KEY (user_profile_id) REFERENCES user_profile (id)
);